Parameters:
  ConformancePackName:
    Description: The name intented to use when creating the organization conformance pack.
    Default: 'TagRemediationConfPack'
    Type: String
  tag1Key:
    Description: Flag to denote that the tag is applied by the AWS Config and Conformance Pack.
    Type: String
    Default: TagAppliedByConfig
  tag1Value: 
    Description: Falg value to denote that the tag is applied by the AWS Config and Conformance Pack.
    Type: String
    Default: 'True'
  S3Bucket:
    Description: s3 Bucket where tag values are stored.
    Type: String
    Default: tstcontmpl
  TagJson: 
    Description: JSON string input for all the Tags.
    Type: String
    Default: 'test'
Resources:
  ResourceTaggingCheck:
    Type: AWS::Config::ConfigRule
    Properties:
      ConfigRuleName: required-tags
      Description: Check resources against the required tags
      Source:
        Owner: AWS
        SourceIdentifier: REQUIRED_TAGS
      InputParameters:
        tag1Key: !Ref tag1Key
        tag1Value: !Ref tag1Value
      Scope:
        ComplianceResourceTypes:
          - AWS::ACM::Certificate
          - AWS::AutoScaling::AutoScalingGroup
          - AWS::CloudFormation::Stack 
          - AWS::CodeBuild::Project
          - AWS::DynamoDB::Table 
          - AWS::EC2::CustomerGateway 
          - AWS::EC2::Instance
          - AWS::EC2::InternetGateway
          - AWS::EC2::NetworkAcl
          - AWS::EC2::NetworkInterface
          - AWS::EC2::RouteTable
          - AWS::EC2::SecurityGroup
          - AWS::EC2::Subnet
          - AWS::EC2::Volume
          - AWS::EC2::VPC
          - AWS::EC2::VPNConnection
          - AWS::EC2::VPNGateway
          - AWS::ElasticLoadBalancing::LoadBalancer
          - AWS::ElasticLoadBalancingV2::LoadBalancer
          - AWS::RDS::DBInstance
          - AWS::RDS::DBSecurityGroup
          - AWS::RDS::DBSnapshot
          - AWS::RDS::DBSubnetGroup
          - AWS::RDS::EventSubscription
          - AWS::Redshift::Cluster
          - AWS::Redshift::ClusterParameterGroup
          - AWS::Redshift::ClusterSecurityGroup
          - AWS::Redshift::ClusterSnapshot
          - AWS::Redshift::ClusterSubnetGroup
          - AWS::S3::Bucket

  MapTaggingRemediation:
    DependsOn: ResourceTaggingCheck
    Type: 'AWS::Config::RemediationConfiguration'
    Properties:
      ConfigRuleName: required-tags
      TargetId: !Sub 'arn:aws:ssm:a<REGION>:<ACCOUNT>:document/SsmDocumentTagRemediation'
      TargetType: 'SSM_DOCUMENT'
      Parameters:
        RequiredTags:
          StaticValue:
            Values:
              - !Sub 
                - '{"${tag1Key}": "${tag1Value}"}'
                - tag1Key: !Ref tag1Key
                  tag1Value: !Ref tag1Value
        AccountID:
          StaticValue:
            Values:
              - !Sub '${AWS::AccountId}'          
        S3Bucket:
          StaticValue:
            Values:
              - Ref: S3Bucket
        TagJson: 
          StaticValue:
            Values:
              - Ref: TagJson
        ConformancePackName:
          StaticValue:
            Values:
              - Ref: ConformancePackName
        ResourceID:
          ResourceValue:
            Value: 'RESOURCE_ID'
        AutomationAssumeRole:
          StaticValue:
            Values:
              - 'arn:aws:iam::<REGION>:role/TagRemediationAutomationRole'
      ExecutionControls:
        SsmControls:
          ConcurrentExecutionRatePercentage: 10
          ErrorPercentage: 10
      Automatic: True
      MaximumAutomaticAttempts: 10
      RetryAttemptSeconds: 600
